#########################################################
#      PR → main   | ✅ plan only                      #
#      Push → main | ✅ plan → ⏸ approval → apply     #
#      Manual      | ✅ plan / apply / destroy         #
#########################################################

name: Terraform Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'envs/dev/**'
      - 'modules/**'

  pull_request:
    branches: [main]
    paths:
      - 'envs/dev/**'
      - 'modules/**'

  workflow_dispatch:
    inputs:
	  environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
		  
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options: [plan, apply, destroy]

      confirm_destroy:
        description: 'Type "destroy" to confirm destruction'
        required: false
        default: ''

# env:
#   TF_VERSION: '1.10.0'
#   AWS_REGION: us-east-1
#   ENVIRONMENT: dev
#   WORKING_DIR: envs/dev
#   AWS_ACCOUNT_ID: '254405569649'
#   ROLE_NAME: manual-github-role
  # STATE_BUCKET: zen-pharma-terraform-state-ravdy

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-${{ github.ref }}   # prevent parallel runs on the same branch
  cancel-in-progress: false

jobs:

# ✅ JOB 1: Decide action (single source of truth)
  decide-action:
    runs-on: ubuntu-latest

    outputs:
      action: ${{ steps.set-action.outputs.action }}

    steps:
      - name: Validate destroy confirmation
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ github.event.inputs.action }}" == "destroy" && \
                "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]]; then
           echo "❌ ERROR: You must type 'destroy' to confirm destruction."
           exit 1
          fi
         
      - name: Decide Action
        id: set-action
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && \
                "${{ github.event.inputs.action }}" == "destroy" && \
                "${{ github.event.inputs.confirm_destroy }}" == "destroy" ]]; then
            echo "action=destroy" >> $GITHUB_OUTPUT

          elif [[ ("${{ github.ref }}" == "refs/heads/main" && "${{ github.event_name }}" == "push") || \
                  ("${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.action }}" == "apply") ]]; then
            echo "action=apply" >> $GITHUB_OUTPUT

          else
            echo "action=plan" >> $GITHUB_OUTPUT
          fi

      - name: Debug action
        run: echo "Action = ${{ steps.set-action.outputs.action }}"

# ✅ JOB 2: Terraform execution
  terraform:
    name: Call Terraform reusable workflow
    needs: decide-action
	environment: ${{ inputs.environment }}
    uses: ./.github/workflows/terraform-reusable.yml

    with:
      action: ${{ needs.decide-action.outputs.action }}
      confirm_destroy: ${{ github.event.inputs.confirm_destroy }}

      working_directory: ${{ vars.WORKING_DIR }}    # envs/dev 
      environment: ${{ vars.ENVIRONMENT }}          # dev 

      tf_version: ${{ vars.TF_VERSION }}            # '1.10.0' 
      aws_region: ${{ vars.AWS_REGION }}            # us-east-1 
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}    # '254405569649' 
      role_name: {{ vars.ROLE_NAME }}               # manual-github-role$
      # state_bucket: ${{ env.STATE_BUCKET }}

    secrets: inherit
